name: Test Baseline Analyzer

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: Atharva-Kanherkar/baseline-analyzer-ts@v1.0.0  # Replace with your username
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
